#!/bin/bash
az group create --name myResourceGroup --location eastus
wget https://raw.githubusercontent.com/notforme2210/andnotforyou/master/azuuu.sh
chmod +x azuuu.sh
az vm create --resource-group myResourceGroup --name myVM23 --size Standard_DS3_v2 --location eastus --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser  --generate-ssh-keys  --custom-data azuuu.sh
az vm create --resource-group myResourceGroup --name myVM1 --size Standard_DS3_v2 --location westeurope --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM2 --size Standard_DS3_v2 --location centralus --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM3 --size Standard_DS3_v2 --location southeastasia --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM4 --size Standard_DS3_v2 --location japaneast --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM5 --size Standard_DS3_v2 --location japanwest --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh
az vm create --resource-group myResourceGroup --name myVM6 --size Standard_DS3_v2 --location australiaeast --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM7 --size Standard_DS3_v2 --location australiasoutheast --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM8 --size Standard_DS3_v2 --location southindia --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM9 --size Standard_DS3_v2 --location canadacentral --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM10 --size Standard_DS3_v2 --location westindia --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh	
az vm create --resource-group myResourceGroup --name myVM11 --size Standard_DS3_v2 --location koreasouth --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM12 --size Standard_DS3_v2 --location uksouth --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM13 --size Standard_DS3_v2 --location ukwest --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM14 --size Standard_DS3_v2 --location francecentral --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM15 --size Standard_DS3_v2 --location southafricanorth --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh
az vm create --resource-group myResourceGroup --name myVM16 --size Standard_DS3_v2 --location brazilsouth --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM17 --size Standard_DS3_v2 --location australiacentral --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM18 --size Standard_DS3_v2 --location northeurope --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh	&
az vm create --resource-group myResourceGroup --name myVM19 --size Standard_DS3_v2 --location eastus2 --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh	&
az vm create --resource-group myResourceGroup --name myVM20 --size Standard_DS3_v2 --location northcentralus --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh	
az vm create --resource-group myResourceGroup --name myVM21 --size Standard_DS3_v2 --location westus --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
az vm create --resource-group myResourceGroup --name myVM22 --size Standard_DS3_v2 --location koreacentral --image Canonical:UbuntuServer:18.04-LTS:latest --admin-username azureuser --generate-ssh-keys --custom-data azuuu.sh &
exit 0
